### ISSUE TITLE
Pins swapped

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#14]
I noticed when I wired up the hardware that I had to swap the two relay GPIOs to get it working.

I think there is a small bug:
Relay IN1 is used as the relay gate pin, you set it to 0 and don't change it in the code.
Relay IN2 is the relay control pin, you toggle this to press the button.

In the diagram IN1 = GPIO 14, IN2 = GPIO 15.

But in the code they are declared the other way around - relay_pin = 14, relay_gate_pin = 15.

**Comment by nebhead** [comment]
Gah!  Thanks for catching this.  I actually have had this comment before which was why I had added the truth table in the readme file - to prove to myself that it was setup correctly.  But I assumed I had documented the picture to the code correctly.  I guess I goofed!  

I'll make the swap in the code so that I don't have to modify the picture at all.  Thanks again!
