### ISSUE TITLE
Use systemd

### ISSUE THREAD

**Issue by hmoffatt** [nebhead/garage-zero#4]
Can I suggesting using systemd instead of adding supervisor? It's a standard part of Raspbian and almost every other linux distro these days.

For the webapp my service file (/etc/systemd/system/garage-zero-webapp.service) is

```
[Unit]
Description=Garage-zero web server
Wants=network.target
After=network.target

[Service]
User=pi
Group=pi
WorkingDirectory=/home/pi/garage-zero
ExecStart=/usr/bin/gunicorn --log-syslog --log-syslog-prefix garage-zero app:app
Restart=always

[Install]
WantedBy=multi-user.target
```

and for control:

```
[Unit]
Description=Garage-zero controller
Wants=network.target
After=network.target

[Service]
User=root
Group=root
WorkingDirectory=/home/pi/garage-zero
ExecStart=/usr/bin/python control.py
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by nebhead** [comment]
Thanks!  It was suggested to me to use systemd initially, instead of supervisor, but then someone else suggested I check out supervisor and I ended up going down that rabbit hole.  I suppose I liked the way that supervisor provided a webUI for monitoring my tasks.  Either is great though - if you don't mind, I'll take your files and include them in the project so that someone installing can chose whichever they want.

**Comment by hmoffatt** [comment]
I submitted a pull request (#7) with my systemd files. Either supervisor is fine, I just prefer systemd because I know it and it's already running rather than adding another package, but I see the advantages of the supervisor web interface.
